version: '3.8'
services:
    redis:
        container_name: redis
        image: redis:alpine
        platform: linux/amd64
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - ./data/redis-data:/data
    redis-insight:
        container_name: redis-insight
        image: redis/redisinsight:latest
        platform: linux/amd64
        ports:
            - "${REDIS_INSIGHT_PORT}:5540"
        volumes:
            - ./data/redis-insight:/data
