version: '3'
services:
    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - ./data/redis:/data
        environment:
            - REDIS_REPLICATION_MODE=master