version: '3'
services:
    redis:
        image: redis:alpine
        container_name: ledgis-redis
        restart: always
        ports:
            - "${REDIS_PORT}:6379"
        command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
        environment:
            - REDIS_REPLICATION_MODE=master
    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: ledgis-redis-commander
        restart: always
        depends_on:
            - redis
        environment:
            - REDIS_HOSTS=local:redis:6379:${REDIS_DB}:${REDIS_PASSWORD} #label:hostname:port:dbIndex:password
        ports:
            - "${REDIS_COMMANDER_PORT}:8081"